### ISSUE TITLE
`install_xdev68k-utils.sh` can fail if build tools like "ninja" are installed

### ISSUE THREAD

**Issue by ggnkua** [yosshin4004/xdev68k#4]
This happens when running `cmake` for `run68k`. Here is the command line log on my MinGW64 install:

```
-- Building for: Ninja
-- The C compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/msys64/mingw64/bi
n/cc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/msys64/home/g
gn/xdev68k/installer_temp/run68mac-master/build
make: *** No targets specified and no makefile found.  Stop.
```

A very easy fix is to change https://github.com/yosshin4004/xdev68k/blob/main/install_xdev68k-utils.sh#L74 to the following:

`cmake -G"Unix Makefiles" ..`

This forces `cmake` to generate plain makefiles, and then the script finishes successfully.

**Comment by yosshin4004** [comment]
Fixed it. Thanks for pointing this out.

**Comment by yosshin4004** [comment]
closed.
