### ISSUE TITLE
README.md「従来の X68K 対応コンパイラとの互換性問題」の項目

### ISSUE THREAD

**Issue by kg68k** [yosshin4004/xdev68k#5]
README.mdの「従来の X68K 対応コンパイラとの互換性問題」の記述について気になったことがあります。

* 破壊レジスタの違い（回避可能） 
https://github.com/yosshin4004/xdev68k/blob/1d286943598304d0f0a16f92a3db7ab73df795f3/README.md?plain=1#L411-L412

m68k-elf-gccの方は `d0-d1/a0-a1/fp0-fp1` でしょうか。

* long double 型のビット幅の違い（回避不能）  
https://github.com/yosshin4004/xdev68k/blob/1d286943598304d0f0a16f92a3db7ab73df795f3/README.md?plain=1#L448-L449

GCC2は12バイトなので、混乱を避けるためここにGCC2も入れたほうがよいかと思います。

**Comment by yosshin4004** [comment]
>m68k-elf-gccの方は d0-d1/a0-a1/fp0-fp1 でしょうか。

ご指摘いただいたとおり d0-d1/a0-a1/fp0-fp1 の間違いです。修正しました。

>GCC2は12バイトなので、混乱を避けるためここにGCC2も入れたほうがよいかと思います。

GCC2は12バイトの旨加筆しました。
gcc 真里子版で検証した内容は gcc 真里子版と明示的に書くようにしました。

**Comment by kg68k** [comment]
ありがとうございます。
